/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Inventory_Management_Java_Application;

import static Inventory_Management_Java_Application.UsersTab.listOfUsers;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hassan
 */
public class customersTab1 extends javax.swing.JFrame {

    /** Creates new form customersTab */
    public customersTab1() {
        initComponents();
        displayCustomersListInJtable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSearchTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jSearchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextCnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextEmail1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextPostcode = new javax.swing.JTextField();
        jClearButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddCustomer = new javax.swing.JButton();
        jButtonEditCustomer = new javax.swing.JButton();
        jButtonDeleteCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CUSTOMERS RECORD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jSearchTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchTextField1KeyReleased(evt);
            }
        });

        jTableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Contact Number", "Email", "Postcode"
            }
        ));
        jTableCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomers);

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSearchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSearchTextField1)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name:");

        jTextFieldFname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name:");

        jTextFieldLname1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contact Number:");

        jTextCnumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");

        jTextEmail1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Postcode:");

        jTextPostcode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jClearButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPostcode)
                                    .addComponent(jTextEmail1)
                                    .addComponent(jTextCnumber)
                                    .addComponent(jTextFieldLname1)
                                    .addComponent(jTextFieldFname)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButtonAddCustomer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAddCustomer.setText("Add Customer");
        jButtonAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCustomerActionPerformed(evt);
            }
        });

        jButtonEditCustomer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonEditCustomer.setText("Edit Customer");
        jButtonEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCustomerActionPerformed(evt);
            }
        });

        jButtonDeleteCustomer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonDeleteCustomer.setText("Delete Customer");
        jButtonDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkIfFieldsEmpty(){
        if(jTextFieldFname.getText().equals("") || jTextFieldLname1.getText().equals("") || jTextCnumber.getText().equals("") || jTextEmail1.getText().equals("") || jTextPostcode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Empty Fields", 0);
            return false;
        }else{
            return true;
        }
    }
    
    
    private void jSearchTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchTextField1KeyReleased
        // TODO add your handling code here:
        //jSearchButton1ActionPerformed(null);
        jSearchButtonActionPerformed(null);
        
    }//GEN-LAST:event_jSearchTextField1KeyReleased

    private void jTableCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomersMouseClicked
        int i = jTableCustomers.getSelectedRow();
        //jTextField_ID.setText(jTable_USERS.getValueAt(rowIndex, 0).toString());
        jTextFieldFname.setText(jTableCustomers.getValueAt(i, 1).toString());
        jTextFieldLname1.setText(jTableCustomers.getValueAt(i, 2).toString());
        jTextCnumber.setText(jTableCustomers.getValueAt(i, 3).toString());
        jTextEmail1.setText(jTableCustomers.getValueAt(i, 4).toString());
        jTextPostcode.setText(jTableCustomers.getValueAt(i, 5).toString());
        //jComboBoxUserType.setSelectedItem(jTableCustomers.getValueAt(i, 4).toString());
        
        
    }//GEN-LAST:event_jTableCustomersMouseClicked

    public void searchData(String query){
        PreparedStatement st;
        ResultSet rs;
        
        try {
            st = MyConnectionDB.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            DefaultTableModel tableModel = (DefaultTableModel)jTableCustomers.getModel();
            tableModel.setRowCount(0);
            
            if(rs.isBeforeFirst()){
                while(rs.next()){
                    Object userObject[] = {rs.getString("CustomerID"),rs.getString("firstName"),rs.getString("lastName"),rs.getString("contactNumber"),rs.getString("Email"),rs.getString("postcode")};
                    tableModel.addRow(userObject);
                }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(UsersTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void jButtonAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCustomerActionPerformed
        // TODO add your handling code here:
        if(checkIfFieldsEmpty()){
            String Fname = jTextFieldFname.getText();
            String Lname = jTextFieldLname1.getText();
            String Cnumber = jTextCnumber.getText();
            String email = jTextEmail1.getText();
            String postcode = jTextPostcode.getText();
            
            Classes.customersPage newCustomer = new Classes.customersPage(0, Fname, Lname, Cnumber, email, postcode);
            Classes.customersPage.insertCustomer(newCustomer);
            JOptionPane.showMessageDialog(null, "Added New Customer");
            
            displayCustomersListInJtable();
            jClearButtonActionPerformed(null);
        }

    }//GEN-LAST:event_jButtonAddCustomerActionPerformed

    private void jButtonEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCustomerActionPerformed
        // TODO add your handling code here:
        if(checkIfFieldsEmpty()){
            if(!jTableCustomers.getSelectionModel().isSelectionEmpty()){
                String Fname = jTextFieldFname.getText();
                String Lname = jTextFieldLname1.getText();
                String Cnumber = jTextCnumber.getText();
                String email = jTextEmail1.getText();
                String postcode = jTextPostcode.getText();
                
                int i = jTableCustomers.getSelectedRow();
                Integer currentCustomerID = Integer.valueOf(jTableCustomers.getValueAt(i, 0).toString());
                
                Classes.customersPage editCustomer = new Classes.customersPage(currentCustomerID, Fname, Lname, Cnumber, email, postcode);
                Classes.customersPage.editCustomer(editCustomer);
                JOptionPane.showMessageDialog(null, "Customer Details Have Been Updated");
                
                displayCustomersListInJtable();
                jClearButtonActionPerformed(null);
            }else{
                JOptionPane.showMessageDialog(null, "Select a user", "No User Selected!", 0);
            }
        }
    }//GEN-LAST:event_jButtonEditCustomerActionPerformed

    
    
    private void jButtonDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCustomerActionPerformed
        if(!jTableCustomers.getSelectionModel().isSelectionEmpty()){
            int decision = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this customer?","Delete Customer", JOptionPane.YES_NO_OPTION);
            if(decision == 0){
                int i = jTableCustomers.getSelectedRow();
                Integer currentCustomerID = Integer.valueOf(jTableCustomers.getValueAt(i, 0).toString());
                Classes.customersPage.deleteCustomer(currentCustomerID);
                JOptionPane.showMessageDialog(null, "Customer Has Been Deleted");

                displayCustomersListInJtable();
                jClearButtonActionPerformed(null);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select a user", "There Is No User Selected!", 0);
        }    
    }//GEN-LAST:event_jButtonDeleteCustomerActionPerformed

    
    
    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        // TODO add your handling code here:
        jTextFieldFname.setText("");
        jTextFieldLname1.setText("");
        jTextCnumber.setText("");
        jTextEmail1.setText("");
        jTextPostcode.setText("");
        jTableCustomers.clearSelection();
        displayCustomersListInJtable();
        jSearchTextField1.setText("");
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
        String searchField = jSearchTextField1.getText();
        if(!searchField.isEmpty()){
            String query = "SELECT * FROM customers WHERE firstName LIKE '%"+searchField+"%' OR lastName LIKE '%"+searchField+"%' OR contactNumber LIKE '%"+searchField+"%' OR Email LIKE '%"+searchField+"%' OR postcode LIKE '%"+searchField+"%'";
            searchData(query);
        }else{
            displayCustomersListInJtable();
        }
    }//GEN-LAST:event_jSearchButtonActionPerformed

    
    
    public static ArrayList<Classes.customersPage> listOfCustomers(){
        ArrayList<Classes.customersPage> listCustomers = new ArrayList<>();
        
        PreparedStatement st;
        ResultSet rs;
        
        try {
            st = MyConnectionDB.getConnection().prepareStatement("SELECT * FROM `customers`");
            rs = st.executeQuery();
            
            Classes.customersPage currentCustomer;
            
            while(rs.next()){
                currentCustomer = new Classes.customersPage(rs.getInt("CustomerID"),rs.getString("firstName"),rs.getString("lastName"),rs.getString("ContactNumber"),rs.getString("Email"),rs.getString("postcode"));
                listCustomers.add(currentCustomer);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Classes.UsersPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listCustomers;
    }
    
    public static void displayCustomersListInJtable(){
        //Classes.UsersPage selectedUser = new Classes.UsersPage();
        ArrayList<Classes.customersPage> listCustomers = listOfCustomers();
        
        String[] JtableHeadings = {"Customer ID","First Name","Last Name","Contact Number", "Email", "Postcode"};
        Object[][] JtableRows = new Object[listCustomers.size()][6];
        
        for(int i=0;i<listCustomers.size();i++){
            JtableRows[i][0] = listCustomers.get(i).getID();
            JtableRows[i][1] = listCustomers.get(i).getFirstName();
            JtableRows[i][2] = listCustomers.get(i).getLastName();
            JtableRows[i][3] = listCustomers.get(i).getContactNumber();
            JtableRows[i][4] = listCustomers.get(i).getEmail();
            JtableRows[i][5] = listCustomers.get(i).getPostcode();
        }
        DefaultTableModel tableDisplayData = new DefaultTableModel(JtableRows,JtableHeadings);
        jTableCustomers.setModel(tableDisplayData);
        jTableCustomers.setRowHeight(45);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customersTab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customersTab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customersTab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customersTab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customersTab1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonDeleteCustomer;
    private javax.swing.JButton jButtonEditCustomer;
    private javax.swing.JButton jClearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField1;
    private static javax.swing.JTable jTableCustomers;
    private javax.swing.JTextField jTextCnumber;
    private javax.swing.JTextField jTextEmail1;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname1;
    private javax.swing.JTextField jTextPostcode;
    // End of variables declaration//GEN-END:variables

}
