/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Management_Java_Application;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hassan
 */
public class manageProductTypes extends javax.swing.JFrame {

    /**
     * Creates new form manageProductTypes
     */
    public manageProductTypes() {
        initComponents();
        displayCategoriesListInJtable();
        
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        jTable2.setBackground(Color.WHITE);
        //jTable2.setForeground(Color.WHITE);
        
        jScrollPane2.setBackground(Color.WHITE);
        jScrollPane2.setForeground(Color.WHITE);
        
        jScrollPane2.getViewport().setBackground(Color.WHITE);
    }
    
    public static void displayProductsListInJtable(int productTypesID){
        Classes.productsPage products = new Classes.productsPage();
        
        ArrayList<Classes.productsPage> productsList = products.productsFromProductTypeID(productTypesID);
        
        String[] heading = {"Products"};
        Object[][] JtableRows = new Object[productsList.size()][1];
        
        
        for(int i=0;i<productsList.size();i++){
         
            JtableRows[i][0] = productsList.get(i).getName();
            System.out.println(productsList.get(i).getName());
            
        }
        
        DefaultTableModel tableDisplayData = new DefaultTableModel(JtableRows,heading);
        jTable2.setModel(tableDisplayData);
        //jTable2.setRowHeight(45);
        
    }
    
    
    public static void displayCategoriesListInJtable(){
        ArrayList<Classes.manageProductType> typesList = Classes.manageProductType.getTypeList();
        String[] jTableHeadings = {"Product Types ID", "Product Types Name"};
        
        Object[][] JtableRows = new Object[typesList.size()][2];
        for(int i=0; i<typesList.size();i++){
            JtableRows[i][0] = typesList.get(i).getID();
            JtableRows[i][1] = typesList.get(i).getName();
        }
        
        DefaultTableModel tableDisplayData = new DefaultTableModel(JtableRows,jTableHeadings);
        jTable1.setModel(tableDisplayData);
        jTable1.setRowHeight(45);
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        newNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addProductTypeBtn = new javax.swing.JButton();
        editProductTypeBtn1 = new javax.swing.JButton();
        deleteProductTypeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Product Types");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("New Product Type Name:");

        addProductTypeBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addProductTypeBtn.setText("Add Product Type");
        addProductTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductTypeBtnActionPerformed(evt);
            }
        });

        editProductTypeBtn1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editProductTypeBtn1.setText("Edit Type Name");
        editProductTypeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductTypeBtn1ActionPerformed(evt);
            }
        });

        deleteProductTypeBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        deleteProductTypeBtn.setText("Delete Product Type");
        deleteProductTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductTypeBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductTypeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newNameTextField)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(editProductTypeBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(deleteProductTypeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(addProductTypeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editProductTypeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteProductTypeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int selectedRow = jTable1.getSelectedRow();
        displayProductsListInJtable(Integer.valueOf(jTable1.getValueAt(selectedRow, 0).toString()));
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void addProductTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductTypeBtnActionPerformed
        if(newNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter A New Product Type Name", "There Is No Product Type Name Entered!", 0);
        }else{
            
            Classes.manageProductType.addNewProductType(newNameTextField.getText());
            JOptionPane.showMessageDialog(null, "New Type Has Been Added");
            displayCategoriesListInJtable();
            newNameTextField.setText("");
            
            displayProductsListInJtable(0);
        }
    }//GEN-LAST:event_addProductTypeBtnActionPerformed

    private void deleteProductTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductTypeBtnActionPerformed
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
            int typeID = (int) (jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            int decision = JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Delete This Product Type","Delete Product Type", JOptionPane.YES_NO_OPTION);
            if(decision == 0){
                Classes.manageProductType.deleteProductType(typeID);
                
                JOptionPane.showMessageDialog(null, "Selected Type Has Been Deleted");
                displayCategoriesListInJtable();
                newNameTextField.setText("");

                displayProductsListInJtable(0);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select A Product Type", "There Is No Type Selected!", 0);
        }
    }//GEN-LAST:event_deleteProductTypeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        newNameTextField.setText("");
        jTable1.clearSelection();
        displayCategoriesListInJtable();
        displayProductsListInJtable(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void editProductTypeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductTypeBtn1ActionPerformed
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
            if(newNameTextField.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter A New Product Type Name", "There Is No Product Type Name Entered!", 0);
            }else{
                
                int typeID = (int) (jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                Classes.manageProductType.editTypeName(typeID, newNameTextField.getText());
                JOptionPane.showMessageDialog(null, "Selected Type Has Been Changed");

                clearBtnActionPerformed(null);
                
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select A Product Type", "There Is No Type Selected!", 0);
        }
    }//GEN-LAST:event_editProductTypeBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageProductTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageProductTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageProductTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageProductTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageProductTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductTypeBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteProductTypeBtn;
    private javax.swing.JButton editProductTypeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JTextField newNameTextField;
    // End of variables declaration//GEN-END:variables
}
