/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Management_Java_Application;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hassan
 */
public class UsersTab extends javax.swing.JFrame {
    /**
     * Creates new form UsersTab
     */
    public UsersTab() {
        initComponents();
        
        displayUsersListInJtable();
        //jTable1.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddUser = new javax.swing.JButton();
        jButtonEditUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jComboBoxUserType = new javax.swing.JComboBox<>();
        jButtonClear1 = new javax.swing.JButton();
        jButtonChangePassword1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSearchTextField1 = new javax.swing.JTextField();
        jSearchButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contact:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("User Type:");

        jTextFieldUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextFieldNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Name", "Mobile Number", "Email", "User Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAddUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAddUser.setText("Add User");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonEditUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonEditUser.setText("Edit User");
        jButtonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUserActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonDeleteUser.setText("Delete User");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        jComboBoxUserType.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Select User-Type ---", "Admin User", "Regular User" }));
        jComboBoxUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserTypeActionPerformed(evt);
            }
        });

        jButtonClear1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonClear1.setText("Clear");
        jButtonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClear1ActionPerformed(evt);
            }
        });

        jButtonChangePassword1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonChangePassword1.setText("Change Password");
        jButtonChangePassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePassword1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USERS RECORD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jSearchTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchTextField1KeyReleased(evt);
            }
        });

        jSearchButton1.setText("Search");
        jSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSearchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSearchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSearchButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonChangePassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNumber)
                                            .addComponent(jTextFieldName)
                                            .addComponent(jTextFieldUsername)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButtonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonChangePassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jComboBoxUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserTypeActionPerformed

    public boolean checkIfFieldsEmpty(){
        if(jTextFieldUsername.getText().equals("") || jTextFieldName.getText().equals("") || jTextFieldNumber.getText().equals("") || jTextFieldEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Empty Fields", 0);
            return false;
        }else{
            return true;
        }
    }
    
    public boolean checkUsername(){
        PreparedStatement st;
        ResultSet rs;
        String query = "SELECT `Username` FROM `userslog` WHERE `Username` = ?";
        
        try {
            st = MyConnectionDB.getConnection().prepareStatement(query);
            st.setString(1, jTextFieldUsername.getText());
            rs = st.executeQuery();
            if(rs.next()){
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(UsersTab.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        //jTextField_ID.setText(jTable_USERS.getValueAt(rowIndex, 0).toString());
        jTextFieldUsername.setText(jTable1.getValueAt(i, 0).toString());
        jTextFieldName.setText(jTable1.getValueAt(i, 1).toString());
        jTextFieldNumber.setText(jTable1.getValueAt(i, 2).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(i, 3).toString());
        jComboBoxUserType.setSelectedItem(jTable1.getValueAt(i, 4).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        if(checkIfFieldsEmpty()){
            if(checkUsername()){
                if(!"--- Select User-Type ---".equals(jComboBoxUserType.getSelectedItem().toString())){
                    String newUsername = jTextFieldUsername.getText();
                    String newName = jTextFieldName.getText();
                    String newNumber = jTextFieldNumber.getText();
                    String newEmail = jTextFieldEmail.getText();
                    String userType = jComboBoxUserType.getSelectedItem().toString();
                    System.out.println(userType);

                    //Classes.UsersPage addUser = new Classes.UsersPage(newUsername, null, newName, newNumber, newEmail, userType)
                   // passwordTab passwordCheck = null;
                    passwordTab passwordCheck = new passwordTab();
                    //passwordTab passwordCheck1 = new passwordTab(newUsername,newName,newNumber,newEmail,userType,passwordCheck);
                    passwordTab.storeData(newUsername,newName,newNumber,newEmail,userType);

                    passwordCheck.pack();
                    passwordCheck.setVisible(true);
                    passwordCheck.setLocationRelativeTo(null);
                    passwordCheck.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    jButtonClear1ActionPerformed(null);
                }else{
                    JOptionPane.showMessageDialog(null, "Select a User-Type", "No User-Type selected", 0);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select a new username", "Username already exists!", 0);
            }
        }
        
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Select a user", "No User Selected!", 0);
        }else{   
            Classes.UsersPage.deleteUser(jTextFieldUsername.getText());
            JOptionPane.showMessageDialog(null,"User Deleted", "Delete User",1);
            displayUsersListInJtable();
            jButtonClear1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClear1ActionPerformed
        jTextFieldUsername.setText("");
        jTextFieldName.setText("");
        jTextFieldNumber.setText("");
        jTextFieldEmail.setText("");
        jComboBoxUserType.setSelectedItem("--- Select User-Type ---");
        jTable1.clearSelection();
        displayUsersListInJtable();
        jSearchTextField1.setText("");
        
    }//GEN-LAST:event_jButtonClear1ActionPerformed

    private void jButtonChangePassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePassword1ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select a user", "No User Selected!", 0);
        } else{
            changePasswordTab.storeData(jTextFieldUsername.getText());
            changePasswordTab changePassword = new changePasswordTab();
            changePassword.pack();
            changePassword.setVisible(true);
            changePassword.setLocationRelativeTo(null);
            changePassword.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            //jButtonClear1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButtonChangePassword1ActionPerformed

    public void searchData(String query){
        PreparedStatement st;
        ResultSet rs;
        
        try {
            st = MyConnectionDB.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
            tableModel.setRowCount(0);
            
            if(rs.isBeforeFirst()){
                while(rs.next()){
                    Object userObject[] = {rs.getString("Username"),rs.getString("FullName"),rs.getString("ContactNumber"),rs.getString("Email"),rs.getString("UserType")};
                    tableModel.addRow(userObject);
                }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(UsersTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButton1ActionPerformed
        String searchField = jSearchTextField1.getText();
        if(!searchField.isEmpty()){
            String query = "SELECT * FROM userslog WHERE FullName LIKE '%"+searchField+"%' OR Username LIKE '%"+searchField+"%' OR ContactNumber LIKE '%"+searchField+"%' OR Email LIKE '%"+searchField+"%' OR UserType LIKE '%"+searchField+"%'";
            searchData(query);
        }else{
            displayUsersListInJtable();
        }
    }//GEN-LAST:event_jSearchButton1ActionPerformed

    private void jSearchTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchTextField1KeyReleased
        // TODO add your handling code here:
        jSearchButton1ActionPerformed(null);
    }//GEN-LAST:event_jSearchTextField1KeyReleased

    private void jButtonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUserActionPerformed
        // TODO add your handling code here:
        //String uName = jTextFieldUsername.getText();
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
            int i = jTable1.getSelectedRow();
            String existingUsername = jTable1.getValueAt(i, 0).toString();
            if(checkIfFieldsEmpty()){
                String uName = jTextFieldUsername.getText();
                String fName = jTextFieldName.getText();
                String num = jTextFieldNumber.getText();
                String email = jTextFieldEmail.getText();
                String uType = jComboBoxUserType.getSelectedItem().toString();
                //System.out.println(existingUsername+"x "+uName+"x ");
                Classes.UsersPage editUser = new Classes.UsersPage(uName, existingUsername, fName, num, email, uType);
                if(existingUsername.equals(uName)){
                    Classes.UsersPage.editUser(editUser);
                    displayUsersListInJtable();
                }else{
                    if(checkUsername()){
                        Classes.UsersPage.editUser(editUser);
                        displayUsersListInJtable();
                    }else{
                        JOptionPane.showMessageDialog(null, "Select a new username", "Username already exists!", 0);
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select a user", "No User Selected!", 0);
        }
    }//GEN-LAST:event_jButtonEditUserActionPerformed

    public static ArrayList<Classes.UsersPage> listOfUsers(){
        ArrayList<Classes.UsersPage> listUsers = new ArrayList<>();
        
        PreparedStatement st;
        ResultSet rs;
        
        try {
            st = MyConnectionDB.getConnection().prepareStatement("SELECT * FROM `userslog`");
            rs = st.executeQuery();
            
            Classes.UsersPage currentUser;
            
            while(rs.next()){
                currentUser = new Classes.UsersPage(rs.getString("Username"),rs.getString("UserPassword"),rs.getString("FullName"),rs.getString("ContactNumber"),rs.getString("Email"),rs.getString("UserType"));
                listUsers.add(currentUser);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Classes.UsersPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listUsers;
    }
    
    public static void displayUsersListInJtable(){
        //Classes.UsersPage selectedUser = new Classes.UsersPage();
        ArrayList<Classes.UsersPage> listUsers = listOfUsers();
        
        String[] JtableHeadings = {"Username","Name","Contact Number", "Email","User Type"};
        Object[][] JtableRows = new Object[listUsers.size()][5];
        
        for(int i=0;i<listUsers.size();i++){
            JtableRows[i][0] = listUsers.get(i).getUsername();
            JtableRows[i][1] = listUsers.get(i).getFullname();
            JtableRows[i][2] = listUsers.get(i).getContactNumber();
            JtableRows[i][3] = listUsers.get(i).getEmail();
            JtableRows[i][4] = listUsers.get(i).getUserType();
        }
        DefaultTableModel tableDisplayData = new DefaultTableModel(JtableRows,JtableHeadings);
        jTable1.setModel(tableDisplayData);
        jTable1.setRowHeight(45);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonChangePassword1;
    private javax.swing.JButton jButtonClear1;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonEditUser;
    private javax.swing.JComboBox<String> jComboBoxUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton1;
    private javax.swing.JTextField jSearchTextField1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
