/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Management_Java_Application;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hassan
 */
public class ViewOrdersTab extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrdersTab
     */
    public ViewOrdersTab() {
        initComponents();
        displayOrdersInJtable();
        
        DigitalReceipt.setLineWrap(true);
        DigitalReceipt.setWrapStyleWord(true);
        Font f = new Font("Courier New", Font.PLAIN,12);
        DigitalReceipt.setFont(f);
        
        //System.out.println(DigitalReceipt.getFont());
        //DigitalReceipt.append("   What A Cruel World");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAllOrders = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DigitalReceipt = new javax.swing.JTextArea();
        openReceiptBTN = new javax.swing.JButton();
        printReceiptBTN1 = new javax.swing.JButton();
        deleteOrderBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Orders");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTableAllOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAllOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAllOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAllOrders);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        DigitalReceipt.setColumns(20);
        DigitalReceipt.setRows(5);
        jScrollPane2.setViewportView(DigitalReceipt);

        openReceiptBTN.setText("Open Receipt");
        openReceiptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openReceiptBTNActionPerformed(evt);
            }
        });

        printReceiptBTN1.setText("Print Receipt");

        deleteOrderBtn.setText("Delete Order");
        deleteOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(openReceiptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printReceiptBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(deleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openReceiptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printReceiptBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableAllOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAllOrdersMouseClicked
        setDigitalReceipt();
    }//GEN-LAST:event_jTableAllOrdersMouseClicked

    private void openReceiptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openReceiptBTNActionPerformed
        if(!jTableAllOrders.getSelectionModel().isSelectionEmpty()){
            
            int orderID = (int) jTableAllOrders.getValueAt(jTableAllOrders.getSelectedRow(), 0);
            String date = jTableAllOrders.getValueAt(jTableAllOrders.getSelectedRow(), 2).toString();
            
            Classes.generateWordReceipt.openReceiptFile(date, orderID);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select An Order", "There Is No Order Selected!", 0);
        }
    }//GEN-LAST:event_openReceiptBTNActionPerformed

    private void deleteOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderBtnActionPerformed
        if(!jTableAllOrders.getSelectionModel().isSelectionEmpty()){
            
            int orderID = (int) jTableAllOrders.getValueAt(jTableAllOrders.getSelectedRow(), 0);
            Classes.getOrderNReceipt.deleteOrder(orderID);
            
            JOptionPane.showMessageDialog(null, "Order Has Been Deleted");
            clearBtnActionPerformed(null);
            displayOrdersInJtable();
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select An Order", "There Is No Order Selected!", 0);
        }
    }//GEN-LAST:event_deleteOrderBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        jTableAllOrders.clearSelection();
        DigitalReceipt.setText("");
        jTextFieldSearch.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    
    
    public void setDigitalReceipt(){
        
        DigitalReceipt.setText("");
        
        DigitalReceipt.setText("   ------------------------Order Information----------------------\n\n");
        
        int orderID = (int) jTableAllOrders.getValueAt(jTableAllOrders.getSelectedRow(), 0);
        //System.out.println("Orders ID: "+orderID);
        ArrayList<Integer> productsIDList = Classes.makeOrder.getProductsIDList(orderID);
        ArrayList<Integer> quantityList = Classes.makeOrder.getProductQuantity(orderID);
        ArrayList<Double> productPrice = Classes.makeOrder.getProductPrice(orderID);
        
        ArrayList<String> productsName = new ArrayList<>();
        //System.out.println("Length "+productsIDList.size());
        for(int i=0; i<productsIDList.size();i++){
            productsName.add(Classes.makeOrder.getProductsNameList(productsIDList.get(i)));
            //System.out.println(quantityList.get(i)+" "+productPrice.get(i)+" "+productsIDList.get(i));
        }
        
        Font f1 = new Font("Courier New", Font.BOLD,12);
        DigitalReceipt.setFont(f1);
        DigitalReceipt.append("   Order ID: "+ orderID+"\n");
        
        Font f2 = new Font("Courier New", Font.PLAIN,12);
        DigitalReceipt.setFont(f2);
        
        //adjust product Names to fit onto word documents
        for(int a=0; a<productsName.size(); a++){
            while(productsName.get(a).length()<25){
                productsName.set(a, productsName.get(a) + " ");
            }
        }
        
        
        for(int x=0; x<productsIDList.size();x++){
            //System.out.println(productsName.get(x));
            DigitalReceipt.append("   "+ productsName.get(x)+"     "+quantityList.get(x)+"   @" + "   £"+productPrice.get(x)+"\n");
        }
        
        String totalPrice = jTableAllOrders.getValueAt(jTableAllOrders.getSelectedRow(), 4).toString().substring(1); 
        DigitalReceipt.append("\n   Total Price:   £"+totalPrice+"\n\n");
        
        DigitalReceipt.append("   ------------------------Customer Information-------------------\n\n");
        Classes.customersPage customerInfo = Classes.customersPage.getCusomerInfo(orderID);
        int customerID = customerInfo.getID();
    
        DigitalReceipt.append("   Customer ID: "+customerID);
        DigitalReceipt.append("\n   First Name: "+customerInfo.getFirstName());
        DigitalReceipt.append("\n   Last Name: "+customerInfo.getLastName());
        DigitalReceipt.append("\n   Contact Number: "+customerInfo.getContactNumber());
        DigitalReceipt.append("\n   Email: "+customerInfo.getEmail());
        DigitalReceipt.append("\n   Postcode: "+customerInfo.getPostcode());
        
    }
    
    
    
    public static void displayOrdersInJtable(){
        Classes.getOrderNReceipt orders = new Classes.getOrderNReceipt();
        ArrayList<Classes.getOrderNReceipt> listOfOrders = orders.allOrders();
        
        String[] JtableHeadings = {"Order ID", "Customer", "Date Created", "Time Created", "Total Price"};
        Object[][] JtableRows = new Object[listOfOrders.size()][5];
        
        for(int i=0; i<listOfOrders.size(); i++){
            JtableRows[i][0] = listOfOrders.get(i).getOrderID();
            JtableRows[i][1] = listOfOrders.get(i).getCustomerName();
            JtableRows[i][2] = listOfOrders.get(i).getDate();
            JtableRows[i][3] = listOfOrders.get(i).getTime();
            JtableRows[i][4] = "£"+listOfOrders.get(i).getTotalPrice();
        }
        
        DefaultTableModel tableDisplayData = new DefaultTableModel(JtableRows,JtableHeadings);
        jTableAllOrders.setModel(tableDisplayData);
        jTableAllOrders.setRowHeight(45);
        
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrdersTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DigitalReceipt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteOrderBtn;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTableAllOrders;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JButton openReceiptBTN;
    private javax.swing.JButton printReceiptBTN1;
    // End of variables declaration//GEN-END:variables
}
